# Generated by Django 3.0.4 on 2020-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Type1', models.CharField(blank=True, max_length=100, null=True)),
                ('Type2', models.CharField(blank=True, max_length=100, null=True)),
                ('Total', models.IntegerField(null=True)),
                ('HP', models.IntegerField(null=True)),
                ('Attack', models.IntegerField(null=True)),
                ('Defense', models.IntegerField(null=True)),
                ('SpAtk', models.IntegerField(null=True)),
                ('SpDef', models.IntegerField(null=True)),
                ('Speed', models.IntegerField(null=True)),
                ('Generation', models.IntegerField(null=True)),
                ('Legendary', models.BooleanField(default=True)),
            ],
        ),
    ]
